export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED_BY_MASTER = 'CANCELLED_BY_MASTER',
  CANCELLED_BY_CLIENT = 'CANCELLED_BY_CLIENT',
  COMPLETED = 'COMPLETED',
}
